/*
 * Cups & Flags — season data.
 * Every year from the first VFL season (1897) to the most recent completed
 * Melbourne Cup and premiership. Each entry: [year, Melbourne Cup winner, premiership club key].
 * Club keys resolve in clubs.js.
 */
(function (root) {
  const SEASONS = [
    [1897, "Gaulus", "essendon"],
    [1898, "The Grafter", "fitzroy"],
    [1899, "Merriwee", "fitzroy"],
    [1900, "Clean Sweep", "melbourne"],
    [1901, "Revenue", "essendon"],
    [1902, "The Victory", "collingwood"],
    [1903, "Lord Cardigan", "collingwood"],
    [1904, "Acrasia", "fitzroy"],
    [1905, "Blue Spec", "fitzroy"],
    [1906, "Poseidon", "carlton"],
    [1907, "Apologue", "carlton"],
    [1908, "Lord Nolan", "carlton"],
    [1909, "Prince Foote", "southmelbourne"],
    [1910, "Comedy King", "collingwood"],
    [1911, "The Parisian", "essendon"],
    [1912, "Piastre", "essendon"],
    [1913, "Posinatus", "fitzroy"],
    [1914, "Kingsburgh", "carlton"],
    [1915, "Patrobas", "carlton"],
    [1916, "Sasanof", "fitzroy"],
    [1917, "Westcourt", "collingwood"],
    [1918, "Night Watch", "southmelbourne"],
    [1919, "Artilleryman", "collingwood"],
    [1920, "Poitrel", "richmond"],
    [1921, "Sister Olive", "richmond"],
    [1922, "King Ingoda", "fitzroy"],
    [1923, "Bitalli", "essendon"],
    [1924, "Backwood", "essendon"],
    [1925, "Windbag", "geelong"],
    [1926, "Spearfelt", "melbourne"],
    [1927, "Trivalve", "collingwood"],
    [1928, "Statesman", "collingwood"],
    [1929, "Nightmarch", "collingwood"],
    [1930, "Phar Lap", "collingwood"],
    [1931, "White Nose", "geelong"],
    [1932, "Peter Pan", "richmond"],
    [1933, "Hall Mark", "southmelbourne"],
    [1934, "Peter Pan", "richmond"],
    [1935, "Marabou", "collingwood"],
    [1936, "Wotan", "collingwood"],
    [1937, "The Trump", "geelong"],
    [1938, "Catalogue", "carlton"],
    [1939, "Rivette", "melbourne"],
    [1940, "Old Rowley", "melbourne"],
    [1941, "Skipton", "melbourne"],
    [1942, "Colonus", "essendon"],
    [1943, "Dark Felt", "richmond"],
    [1944, "Sirius", "fitzroy"],
    [1945, "Rainbird", "carlton"],
    [1946, "Russia", "essendon"],
    [1947, "Hiraji", "carlton"],
    [1948, "Rimfire", "melbourne"],
    [1949, "Foxzami", "essendon"],
    [1950, "Comic Court", "essendon"],
    [1951, "Delta", "geelong"],
    [1952, "Dalray", "geelong"],
    [1953, "Wodalla", "collingwood"],
    [1954, "Rising Fast", "footscray"],
    [1955, "Toparoa", "melbourne"],
    [1956, "Evening Peal", "melbourne"],
    [1957, "Straight Draw", "melbourne"],
    [1958, "Baystone", "collingwood"],
    [1959, "Macdougal", "melbourne"],
    [1960, "Hi Jinx", "melbourne"],
    [1961, "Lord Fury", "hawthorn"],
    [1962, "Even Stevens", "essendon"],
    [1963, "Gatum Gatum", "geelong"],
    [1964, "Polo Prince", "melbourne"],
    [1965, "Light Fingers", "essendon"],
    [1966, "Galilee", "stkilda"],
    [1967, "Red Handed", "richmond"],
    [1968, "Rain Lover", "carlton"],
    [1969, "Rain Lover", "richmond"],
    [1970, "Baghdad Note", "carlton"],
    [1971, "Silver Knight", "hawthorn"],
    [1972, "Piping Lane", "carlton"],
    [1973, "Gala Supreme", "richmond"],
    [1974, "Think Big", "richmond"],
    [1975, "Think Big", "northmelbourne"],
    [1976, "Van Der Hum", "hawthorn"],
    [1977, "Gold and Black", "northmelbourne"],
    [1978, "Arwon", "hawthorn"],
    [1979, "Hyperno", "carlton"],
    [1980, "Beldale Ball", "richmond"],
    [1981, "Just A Dash", "carlton"],
    [1982, "Gurner's Lane", "carlton"],
    [1983, "Kiwi", "hawthorn"],
    [1984, "Black Knight", "essendon"],
    [1985, "What A Nuisance", "essendon"],
    [1986, "At Talaq", "hawthorn"],
    [1987, "Kensei", "carlton"],
    [1988, "Empire Rose", "hawthorn"],
    [1989, "Tawrrific", "hawthorn"],
    [1990, "Kingston Rule", "collingwood"],
    [1991, "Let's Elope", "hawthorn"],
    [1992, "Subzero", "westcoast"],
    [1993, "Vintage Crop", "essendon"],
    [1994, "Jeune", "westcoast"],
    [1995, "Doriemus", "carlton"],
    [1996, "Saintly", "northmelbourne"],
    [1997, "Might And Power", "adelaide"],
    [1998, "Jezabeel", "adelaide"],
    [1999, "Rogan Josh", "northmelbourne"],
    [2000, "Brew", "essendon"],
    [2001, "Ethereal", "brisbane"],
    [2002, "Media Puzzle", "brisbane"],
    [2003, "Makybe Diva", "brisbane"],
    [2004, "Makybe Diva", "portadelaide"],
    [2005, "Makybe Diva", "sydney"],
    [2006, "Delta Blues", "westcoast"],
    [2007, "Efficient", "geelong"],
    [2008, "Viewed", "hawthorn"],
    [2009, "Shocking", "geelong"],
    [2010, "Americain", "collingwood"],
    [2011, "Dunaden", "geelong"],
    [2012, "Green Moon", "sydney"],
    [2013, "Fiorente", "hawthorn"],
    [2014, "Protectionist", "hawthorn"],
    [2015, "Prince Of Penzance", "hawthorn"],
    [2016, "Almandin", "westernbulldogs"],
    [2017, "Rekindling", "richmond"],
    [2018, "Cross Counter", "westcoast"],
    [2019, "Vow And Declare", "richmond"],
    [2020, "Twilight Payment", "richmond"],
    [2021, "Verry Elleegant", "melbourne"],
    [2022, "Gold Trip", "geelong"],
    [2023, "Without A Fight", "collingwood"],
    [2024, "Knight's Choice", "brisbane"],
    [2025, "Half Yours", "brisbane"],
  ].map(([year, horse, club]) => ({ year, horse, club }));

  // "Did you know?" notes shown once a year is complete.
  const TRIVIA = {
    1897: "The VFL's first season. Essendon took the flag via a round-robin finals series, with no grand final.",
    1916: "Only four clubs took the field in 1916 because of the Great War.",
    1924: "No grand final was played; Essendon won a round-robin finals series.",
    1930: "Phar Lap won as the 8/11 favourite, the shortest-priced winner in Cup history.",
    1932: "Peter Pan won the first of his two Cups.",
    1934: "Peter Pan's second Cup, won on a heavy track.",
    1948: "Melbourne won the grand final replay after a drawn grand final against Essendon.",
    1954: "Footscray's first VFL premiership.",
    1965: "Light Fingers gave Bart Cummings the first of his record 12 Melbourne Cups.",
    1966: "St Kilda's only premiership, won by a single point over Collingwood.",
    1968: "Rain Lover won the first of back-to-back Cups (1968–69).",
    1974: "Think Big won the first of back-to-back Cups (1974–75).",
    1977: "North Melbourne won the grand final replay after a drawn grand final.",
    1990: "Kingston Rule set the race record time of 3:16.3.",
    1992: "West Coast became the first club from outside Victoria to win the premiership.",
    1993: "Vintage Crop became the first international-trained (Irish) Cup winner.",
    1997: "Adelaide's first AFL premiership.",
    2003: "Brisbane completed a premiership three-peat (2001–03). Makybe Diva began hers.",
    2005: "Makybe Diva's third straight Cup. Sydney ended a 72-year premiership drought.",
    2008: "Viewed was Bart Cummings' 12th and final Melbourne Cup.",
    2010: "Collingwood won the grand final replay after a drawn grand final against St Kilda.",
    2015: "Michelle Payne became the first female jockey to win the Cup, on Prince Of Penzance. Hawthorn completed a three-peat.",
    2016: "The Western Bulldogs ended a 62-year premiership drought.",
    2017: "Richmond ended a 37-year premiership drought.",
    2020: "Richmond won the first grand final played outside Victoria, at the Gabba.",
    2021: "Melbourne ended a 57-year drought in a grand final played in Perth.",
    2025: "Brisbane went back-to-back, beating Geelong in the grand final.",
  };

  const ERAS = [
    { from: 1897, to: 1914, name: "The Early VFL", tone: "sepia" },
    { from: 1915, to: 1918, name: "The Great War Years", tone: "sepia" },
    { from: 1919, to: 1938, name: "Between the Wars", tone: "sepia" },
    { from: 1939, to: 1945, name: "The Second World War", tone: "sepia" },
    { from: 1946, to: 1969, name: "The Post-War Boom", tone: "faded" },
    { from: 1970, to: 1989, name: "The Colour TV Era", tone: "retro" },
    { from: 1990, to: 1999, name: "The AFL Goes National", tone: "modern" },
    { from: 2000, to: 9999, name: "The Modern Era", tone: "modern" },
  ];

  const eraFor = (year) => ERAS.find((e) => year >= e.from && year <= e.to);

  const api = { SEASONS, TRIVIA, ERAS, eraFor };
  root.HF = Object.assign(root.HF || {}, api);
  if (typeof module !== "undefined") module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
